name: Quick Start Flow Test
on:
  # Only run this on pushes to master
  push:
    branches:
    - master

  # And when PRs operations are done
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull the Docker image
      run: docker-compose pull

    - name: Generate the master key
      run: docker-compose run --no-deps --rm conjur data-key generate > data_key

    - name: Load master key as an environment variable
      run: echo ::set-env name=CONJUR_DATA_KEY::$(cat data_key)

    - name: Start the Conjur OSS environment
      run: docker-compose up -d

    - name: Wait for Conjur to be ready
      run: docker-compose exec -T conjur conjurctl wait -r 30 -p 80

    - name: Create an admin account
      run: docker-compose exec conjur conjurctl account create myConjurAccount > admin_data

    - name: Connect the Conjur client to the Conjur server
      run: docker-compose exec client conjur init -u conjur -a myConjurAccount

      # todo fix this step
    - name: Log in to Conjur as admin
      run: docker-compose exec client conjur authn login -u admin -p "$(cat admin_data | grep "API key" | awk '{ print $NF }')"

    - name: Load the sample policy
      run: docker-compose exec client conjur policy load root policy/BotApp.yml > my_app_data

      # todo remove?
    - name: Log out of Conjur
      run: docker-compose exec client conjur authn logout

    
